module.exports={
    entry:"./src/app/Index.js",
    output:{
        path:__dirname+"/src/public",
        filename:"Bundle.js"
    },
    module:{
        rules:[
            {
                use:"babel-loader",
                test:/\.js$/,
                exclude:"/node_modules/"
            }
        ]
    }
};